import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./Redux/Provider";
import Navbar from "../components/Navbar";
import { SessionWrapper } from "../widgets/SessionWrapper";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Meshverse",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <SessionWrapper>
      <html lang="en">
        <body className={`font-primary background-primary text-neutral-300 `}>
          <Providers>
            <Navbar />
            {children}
          </Providers>
        </body>
      </html>
    </SessionWrapper>
  );
}
